"""
===============================================================================
[File] visualize_pseudo_boxes.py

[Purpose]
Visualize pseudo bounding boxes generated by open-vocabulary detectors.

[Why this file is needed]
Before using pseudo boxes for label-free groundedness, we must visually inspect
whether the OVD model actually localizes defect-like regions.

This is especially important because OWL-ViT may produce:
1) no boxes,
2) low-confidence boxes,
3) overly large boxes covering surface regions instead of defects.

Input:
    outputs/pseudo_boxes_*/pseudo_boxes_owlvit.json

Output:
    outputs/pseudo_boxes_*/visualized_pseudo_boxes/*.png
===============================================================================
"""

import json
from pathlib import Path

from PIL import Image
import matplotlib.pyplot as plt
import matplotlib.patches as patches


PROJECT_ROOT = Path("/Users/hy/PycharmProjects/PythonProject/Defect_VLM_Project")
OUTPUT_BASE_DIR = PROJECT_ROOT / "outputs"


def find_latest_pseudo_box_file() -> Path:
    files = list(OUTPUT_BASE_DIR.glob("pseudo_boxes_*/pseudo_boxes_owlvit.json"))
    if not files:
        raise FileNotFoundError("pseudo_boxes_owlvit.json 파일을 찾을 수 없습니다.")
    return max(files, key=lambda p: p.stat().st_mtime)


def visualize_one_item(item: dict, save_dir: Path):
    image_path = Path(item["image_path"])
    image_name = item["image_name"]
    pseudo_boxes = item.get("pseudo_boxes", [])

    if not image_path.exists():
        print(f"[WARN] 이미지 없음: {image_path}")
        return

    image = Image.open(image_path).convert("RGB")

    fig, ax = plt.subplots(figsize=(8, 6))
    ax.imshow(image)
    ax.axis("off")

    title = f"{image_name} | {item.get('dataset_type', '')} | boxes={len(pseudo_boxes)}"
    ax.set_title(title, fontsize=10)

    for box in pseudo_boxes:
        x1, y1, x2, y2 = box["xyxy"]
        w = x2 - x1
        h = y2 - y1

        rect = patches.Rectangle(
            (x1, y1),
            w,
            h,
            linewidth=2,
            edgecolor="red",
            facecolor="none"
        )
        ax.add_patch(rect)

        label = (
            f"{box.get('prompt', '')}\n"
            f"score={box.get('score', 0):.4f}, "
            f"zone={box.get('spatial_zone', '')}, "
            f"area={box.get('area_ratio', 0):.4f}"
        )

        ax.text(
            x1,
            max(y1 - 5, 0),
            label,
            fontsize=7,
            color="yellow",
            bbox=dict(facecolor="black", alpha=0.6, pad=2)
        )

    save_path = save_dir / f"{Path(image_name).stem}_pseudo.png"
    plt.savefig(save_path, dpi=200, bbox_inches="tight")
    plt.close(fig)

    print(f"[SAVE] {save_path.name}")


def main():
    pseudo_file = find_latest_pseudo_box_file()
    print(f"[*] pseudo box file: {pseudo_file}")

    with open(pseudo_file, "r", encoding="utf-8") as f:
        data = json.load(f)

    save_dir = pseudo_file.parent / "visualized_pseudo_boxes"
    save_dir.mkdir(parents=True, exist_ok=True)

    for item in data:
        visualize_one_item(item, save_dir)

    print("\n[완료] pseudo box 시각화 저장")
    print(save_dir)


if __name__ == "__main__":
    main()